### ISSUE TITLE
Test for PR firmware isn't precise enough

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1955]
The current test for whether a firmware version came from a pull request only checks for "starts with 0.". However, custom device firmware has version numbers that start with 0. but are not pull request builds, which causes the desktop app to think these are pre-release builds and enables all firmware features.

PR firmware always starts with 0.0. Update the connector to use this more precise check, so it doesn't accidentally pick up custom device firmware builds.

**Comment by neilenns** [comment]
Here's the script from the firmware build that shows how the pull request version is calculated. Notice it always starts with 0.0.

```yaml
      - name: Run PlatformIO
        env:
          VERSION: "0.0.${{ github.event.number }}"
        run: pio run
```
